In [1]:
import numpy as np
import pandas as pd

# Loading and curating the dataset

## Data can come in all formats, but a csv file is one of the most common due to its simplicity and intergration with spreadsheets. The data we will be using for this turorial is real, raw data from the Gilestro lab, where we track and record the movement of fruit flies using machine vision. The tracking is able to discern small movements in the fly that can robustly record the flies several times per second giving a multiude of variables to work with

In [7]:
df = pd.read_csv('/home/lab/Desktop/ReCoDE-HMMs-for-the-discovery-of-behavioural-states/data/recode.csv', index_col = 'id')

/tmp/ipykernel_15424/313462215.py:1: DtypeWarning: Columns (10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/home/lab/Desktop/ReCoDE-HMMs-for-the-discovery-of-behavioural-states/data/recode.csv', index_col = 'id')

#### Lets have a look at how the data is structured

In [8]:
df

,t,x,y,w,h,phi,max_velocity,mean_velocity,distance,moving,micro,walk
id,,,,,,,,,,,,
2016-04-04_17-39-22_033aee|01,31140,0.566093,0.068208,0.047097,0.020538,112.260000,75.662162,11.134010,1.670102,True,False,True
2016-04-04_17-39-22_033aee|01,31200,0.434314,0.068402,0.047802,0.020524,95.705263,20.224544,6.487670,1.848986,True,False,True
2016-04-04_17-39-22_033aee|01,31260,0.431646,0.070613,0.047822,0.020122,66.097826,34.824007,7.406405,2.044168,True,False,True
2016-04-04_17-39-22_033aee|01,31320,0.362770,0.072714,0.045966,0.020991,96.191489,21.871509,6.122182,1.726455,True,False,True
2016-04-04_17-39-22_033aee|01,31380,0.565164,0.064631,0.049321,0.021181,101.063830,21.275450,6.070268,1.711816,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
2016-04-04_17-39-05_009aee|20,608100,0.313964,0.055713,0.038698,0.018182,74.215909,25.285919,3.244659,0.856590,True,False,True
2016-04-04_17-39-05_009aee|20,608160,0.219079,0.054995,0.036436,0.018559,78.388889,32.875983,4.732367,1.277739,True,False,True
2016-04-04_17-39-05_009aee|20,608220,0.861160,0.040692,0.044964,0.017654,54.629213,6.837207,1.579335,0.421682,True,False,True
2016-04-04_17-39-05_009aee|20,608280,0.818817,0.040500,0.046437,0.016646,61.750000,12.384508,1.515177,0.400007,True,False,True
2016-04-04_17-39-05_009aee|20,608340,0.715814,0.046272,0.046770,0.016830,25.255319,10.540926,1.710175,0.241135,True,False,True

#### In the index column we have the ID which is unique per fly and will allow us to filter and apply methods to just one fly at a time. The next most important variable is 't' or time, as we are working with time series data we must ensure this is strucutred properly i.e. in sequential order and at regular intervals (the later we will go over). The rest are various variables per each timestamp, for this turorial we'll only be interested in 'moving', 'micro', and 'walk'.

In [ ]:
# check for nan values

In [ ]:
# bin to a higher time interval

In [ ]:
# check every if any of the time series skip time point (interpolate)

In [ ]:
# change variables into numerical categotries